// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: location-history-management.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LocationHistoryManagement_UpdateUserLocation_FullMethodName = "/main.LocationHistoryManagement/UpdateUserLocation"
)

// LocationHistoryManagementClient is the client API for LocationHistoryManagement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LocationHistoryManagementClient interface {
	UpdateUserLocation(ctx context.Context, in *LocationInfo, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type locationHistoryManagementClient struct {
	cc grpc.ClientConnInterface
}

func NewLocationHistoryManagementClient(cc grpc.ClientConnInterface) LocationHistoryManagementClient {
	return &locationHistoryManagementClient{cc}
}

func (c *locationHistoryManagementClient) UpdateUserLocation(ctx context.Context, in *LocationInfo, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, LocationHistoryManagement_UpdateUserLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LocationHistoryManagementServer is the server API for LocationHistoryManagement service.
// All implementations must embed UnimplementedLocationHistoryManagementServer
// for forward compatibility.
type LocationHistoryManagementServer interface {
	UpdateUserLocation(context.Context, *LocationInfo) (*emptypb.Empty, error)
	mustEmbedUnimplementedLocationHistoryManagementServer()
}

// UnimplementedLocationHistoryManagementServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLocationHistoryManagementServer struct{}

func (UnimplementedLocationHistoryManagementServer) UpdateUserLocation(context.Context, *LocationInfo) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserLocation not implemented")
}
func (UnimplementedLocationHistoryManagementServer) mustEmbedUnimplementedLocationHistoryManagementServer() {
}
func (UnimplementedLocationHistoryManagementServer) testEmbeddedByValue() {}

// UnsafeLocationHistoryManagementServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LocationHistoryManagementServer will
// result in compilation errors.
type UnsafeLocationHistoryManagementServer interface {
	mustEmbedUnimplementedLocationHistoryManagementServer()
}

func RegisterLocationHistoryManagementServer(s grpc.ServiceRegistrar, srv LocationHistoryManagementServer) {
	// If the following call pancis, it indicates UnimplementedLocationHistoryManagementServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LocationHistoryManagement_ServiceDesc, srv)
}

func _LocationHistoryManagement_UpdateUserLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocationInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationHistoryManagementServer).UpdateUserLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocationHistoryManagement_UpdateUserLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationHistoryManagementServer).UpdateUserLocation(ctx, req.(*LocationInfo))
	}
	return interceptor(ctx, in, info, handler)
}

// LocationHistoryManagement_ServiceDesc is the grpc.ServiceDesc for LocationHistoryManagement service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LocationHistoryManagement_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "main.LocationHistoryManagement",
	HandlerType: (*LocationHistoryManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateUserLocation",
			Handler:    _LocationHistoryManagement_UpdateUserLocation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "location-history-management.proto",
}
